### ISSUE TITLE
Exports not working as expected

### ISSUE THREAD

**Issue by colinmeinke** [serieseight/tinyscroll#6]
```
Using named and default exports together.
Consumers of your bundle will have to use tinyscroll['default'] to access the default export,
which may not be what you want.
Use `exports: 'named'` to disable this warning.
See https://github.com/rollup/rollup/wiki/JavaScript-API#exports for more information
```

This breaks default UMD use such as in the `/examples` directory and codepen examples https://codepen.io/colinmeinke/pen/eBZZVo

Just out of interest @aryehraber

**Comment by aryehraber** [comment]
Ah interesting... I've not run into this issue before because Webpack/Babel take care of this out of the box.

https://codepen.io/aryeh/project/editor/ZwvMOV

I guess to keep it available as a 'drop in' solution, this should be fixed.
